### ISSUE TITLE
Redundante Daten in Auth_User Datenbank

### ISSUE THREAD

**Issue by flix318** [simonhauck/M-AI-eVoting#13]
Redundante Daten vermeiden in den Datenbanken auth_user und helis_auth_user. Zur Zeit aufgrund der verwendeten Packages nicht umsetzbar. Eventuelle noch einmal prüfen.

**Comment by simonhauck** [comment]
Aufgrund der Django Struktur und den verwendeten Packages nichts anders umsetzbar
