### ISSUE TITLE
Workshop KW41 

### ISSUE THREAD

**Issue by flix318** [simonhauck/M-AI-eVoting#17]
Aufgaben die im Workshop in der KW41 (Fr-So) erledigt werden sollen.

- [x] Neues Frontend in der VM einpflegen

- [x] Gruppenberechtigung bei LDAP Anmeldung für Nutzer abfragen.

- [x] Neuen Trustee hinzufügen. 

- [ ] Problem mit den Zeiten im Helios System fixen

**Comment by simonhauck** [comment]
Time problem is on hold
