### ISSUE TITLE
Update Design

### ISSUE THREAD

**Issue by KingKaro** [simonhauck/M-AI-eVoting#39]
- [x] Remove Type from "Create Election"

- [x] Add space between text and textbox in "Add Questions"

- [x] Remove result type in "Add Questions"

- [x] Fix Audit in "Helios Voting Booth"

- [x] Fix loading animation in "Helios Single-Ballot Verifier"/...

- [x] Update Design "Helios Single-Ballot Verifier" 

- [x] Update Design "Helios Election Verifier" (election tally)

- [x] Burger Menü anpassen

**Comment by flix318** [comment]
- [ ] Voter Auswahl Upload und anderer Button Styles tauschen.
