### ISSUE TITLE
Meeting Osman 01.10.2019

### ISSUE THREAD

**Issue by flix318** [simonhauck/M-AI-eVoting#9]
1. VM Zeigen

- Entwicklungsumgebung zeigen
- LDAP Zeigen

2. Helios System Wahl zeigen

- Problem: Zeitstempel
- Problem: IP-Adresse
- Problem: UI
- Problem: Stimmauszählen mit Passwort geht nicht
- Problem: Lokale Benutzer, dort wird das Passwort im Klartext gespeichert.

3. Angenommene Vorschläge

**Aktuelle Arbeitspakete**
- LDAP, Benutzer Authentifizieren und mit Usernamen anfragen.
- Front-End Seitenaufbau.

**Comment by simonhauck** [comment]
done
